### ISSUE TITLE
Search docs unsupported simplified chinese

### ISSUE THREAD

**Issue by zhongzhq** [dldl/sphinx-server#33] opened 2019-03-25 23:30 UTC
No results were found when searching for Chinese content in the document. It could be a character format support issue.

**Comment by quentinus95** [comment] 2019-04-16 08:44
Can you confirm you can't reproduce this issue with a vanilla installation of Sphinx (without using code from this repo) with / without read the docs theme?

**Comment by quentinus95** [comment] 2019-05-09 05:24
Closing as no answer.

**Closed as completed by quentinus95** 2019-05-09 05:24 UTC
